CONST TRUE = -1, false = 0
CONST DEFAULT_HOST = "localhost"
CONST HOST_PORT = 25123

CONST AIRCRAFT_SIZE = 6
CONST BATTLESHIP_SIZE = 5
CONST CRUISER_SIZE = 4
CONST DESTROYER_SIZE = 3
CONST SUBMARINE_SIZE = 2

CONST SHIPS$ = "ABCCDDDSSSS"
